[package]
name = "framedump"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ehframe = { path = "../cargo-trace/ehframe", version = "*" }
object = "0.29.0"