[default]
limits = { form = "64 kB", json = "32 MiB", string = "32 MiB" }

[debug]
log_level = "normal"
logged_in = true

[release]
log_level = "normal"
logged_in = false
address = "0.0.0.0"
port = 8000
template_dir = "tail2-server/templates/"
secret_key = "hRYyVRAiMyxpw5sBB1XeCMN1kFsDCqKvBi2QJxBVHQk="