[package]
name = "xtask"
version = "0.1.0"
edition = "2021"
[[bin]]
name = "xtask"
path = "src/main.rs"

[dependencies]
anyhow = "1.0.68"
clap = { version = "4.0", features = ["derive"] }
ctrlc = "3.2.4"

[features]
deploy = []
